#! /bin/sh
### BEGIN INIT INFO
# Provides:          arris
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:      $portmap
# Should-Stop:       $portmap
# X-Start-Before:    nis
# X-Stop-After:      nis
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO
TARGET_DIR="/home/signal/redphone2/"
GREP_BY="tornado_red"

export TORNADO=1

usage() {
    echo "$0 {start|stop|restart|status|update}"
}

start() {
	PIDS=$(pids)
    if [ -n "$PIDS" ]; then
        echo "daemons already running"
        status
    else
    echo "starting daemons"
		cd $TARGET_DIR
		python ${GREP_BY}.py 8880 &

    fi
}

restart() {
    stop
    echo "sleeping..."
    sleep 1
    start
}

pids() {
	echo $(ps ax | grep $GREP_BY | grep -v grep | awk '{print $1;}')
}

stop() {
	PIDS=$(pids)
	if [ -n "$PIDS" ]; then
        echo "stopping daemons"
        for pid in $PIDS; do
            kill $pid
        done
    else
        echo "no daemons running"
    fi
}

status() {
	ps ax | grep $GREP_BY | grep -v grep
}

update() {
	hg push
 	ssh $TARGET "cd $TARGET_DIR && hg update && ./alicectl restart && ./alicectl status" &
}

action=$1
#shift
case $action in
    "start") start;;
    "stop") stop;;
    "status") status;;
    "restart") restart;;
    "update") update;;
    *) echo $(usage);;
esac

