# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CompressedInitiateSignal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CompressedInitiateSignal.proto',
  package='redphone',
  serialized_pb=_b('\n\x1e\x43ompressedInitiateSignal.proto\x12\x08redphone\"s\n\x18\x43ompressedInitiateSignal\x12\x11\n\tinitiator\x18\x01 \x02(\t\x12\x11\n\tsessionId\x18\x02 \x02(\x05\x12\x0c\n\x04port\x18\x03 \x02(\x05\x12\x12\n\nserverName\x18\x04 \x02(\t\x12\x0f\n\x07version\x18\x05 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMPRESSEDINITIATESIGNAL = _descriptor.Descriptor(
  name='CompressedInitiateSignal',
  full_name='redphone.CompressedInitiateSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initiator', full_name='redphone.CompressedInitiateSignal.initiator', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='redphone.CompressedInitiateSignal.sessionId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='redphone.CompressedInitiateSignal.port', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverName', full_name='redphone.CompressedInitiateSignal.serverName', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='redphone.CompressedInitiateSignal.version', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['CompressedInitiateSignal'] = _COMPRESSEDINITIATESIGNAL

CompressedInitiateSignal = _reflection.GeneratedProtocolMessageType('CompressedInitiateSignal', (_message.Message,), dict(
  DESCRIPTOR = _COMPRESSEDINITIATESIGNAL,
  __module__ = 'CompressedInitiateSignal_pb2'
  # @@protoc_insertion_point(class_scope:redphone.CompressedInitiateSignal)
  ))
_sym_db.RegisterMessage(CompressedInitiateSignal)


# @@protoc_insertion_point(module_scope)
